name: free-disk-space
description: Free disk space by removing unused packages and images

runs:
  using: "composite"
  steps:
    - name: Remove unused files
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}
      run: |
          set +x

          sudo df -h

          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

          sudo df -h
