name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Artifacts:
    uses: ./.github/workflows/-build-artifacts.yml
    secrets: inherit
    with:
      workflow-name: main.yml
